version: "3.8"
services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

networks:

  default:
    driver: bridge
